In [5]:
import torch
import matplotlib as plt
import numpy as np
import pandas as pd

### Introduction to Tensors


In [ ]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7, 8], 
                       [0, 10]])
MATRIX

tensor([[ 7,  8],
        [ 0, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3], 
                        [3, 6, 9], 
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
### Random Tensors
"""Important because the way neural nets learn is that they start with tensors 
and adjust those random numbers to better represent data"""

random_tensor = torch.rand(3, 4)
print(random_tensor)

tensor([[0.6142, 0.4865, 0.6097, 0.2356],
        [0.6954, 0.8724, 0.4855, 0.1563],
        [0.1925, 0.1770, 0.3267, 0.9673]])


In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape to image tensor

random_image_size_tensor = torch.rand(3, 244, 244) #colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

In [ ]:
#Create a tensor of all zeros

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#ones

ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#torch.arange()

oneten = torch.arange(start=0, end=11, step=1)
oneten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
tenzero = torch.zeros_like(input=oneten)
tenzero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

Three common errors:
1. Tensor not right datatype - find datatype by tensor.dtype
2. Tensor not right shape - find shape by tensor.shape
3. Tensor not the right device - find device by tensor.device

In [ ]:
#Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, #datatype
                               device=None, #device
                               requires_grad=False) #whether or not to track gradient

float_32_tensor

tensor([3., 6., 9.])

### Tensor Operations

In [ ]:
#Create a tensor and add 10
tensor = torch.tensor([1, 2, 3])
tensor + 10

# torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
# multiply 10
mtensor = tensor * 10

# torch.mul(tensor, 10)

In [ ]:
# divide 10
mtensor / 10

tensor([1., 2., 3.])

In [ ]:
mtensor - 10

tensor([ 0, 10, 20])

In [ ]:
#matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

### Tensor Aggregation

In [ ]:
#Create a tensor

x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Find the min

torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#Find the max

torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#Find the mean
#torch.mean() requires a float 32

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Reshaping and Stacking

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked


tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

### Indexing

In [ ]:
#Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Let's index on our new tensoer
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Let's index on the middle bracket (dim=1)
x[0, 0]

tensor([1, 2, 3])

In [ ]:
x[0][0][:]

tensor([1, 2, 3])

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
#Use ':' to select all of target dimension
x[:, 1]

tensor([[4, 5, 6]])

In [ ]:
x[0, 1]

tensor([4, 5, 6])

In [ ]:
#Get all values if 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

### Squeezing, unsqueezing and permuting

In [10]:
#SQUEEZING 
#Returns a tensor with all specified dimensions of input of size 1 removed.

x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [11]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [12]:
y = torch.squeeze(x, 0)
y.size()


torch.Size([2, 2, 2])

In [13]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [14]:
y = torch.squeeze(x, (1, 2, 3))
torch.Size([2, 2, 2])

torch.Size([2, 2, 2])

In [8]:
#UNSQUEEZING
#Returns a new tensor with a dimension of size 1 inserted at the specified position.
x = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(x, 0)

tensor([[1, 2, 3, 4]])

In [9]:
torch.unsqueeze(x, 1)

tensor([[1],
        [2],
        [3],
        [4]])

In [15]:
#PERMUTE
#Returns a view of the original tensor input with its dimensions permuted.
x = torch.randn(2, 3, 5)
x.size()

torch.Size([2, 3, 5])

In [16]:
torch.permute(x, (2, 0, 1)).size()

torch.Size([5, 2, 3])